#!/usr/bin/env bash
# build_standalone.sh — Create and build a standalone optimized chdman
#
# Usage:
#   bash build_standalone.sh <mame-source-dir> [output-dir]
#
# Arguments:
#   mame-source-dir   Path to a MAME source tree (e.g. /c/Sources/mame286sources)
#   output-dir        Output directory (default: ./chdman_build)
#
# Examples:
#   bash build_standalone.sh /c/Sources/mame286sources
#   bash build_standalone.sh /c/Sources/mame287sources ./my_build
#
# Requirements (MSYS2/MinGW64):
#   pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-cmake
#   pacman -S mingw-w64-x86_64-uasm   # optional — enables LZMA ASM decoder (+29% LZMA speed)

set -e

MAME_SRC="${1:?ERROR: MAME source directory required.
Usage: bash build_standalone.sh <mame-source-dir> [output-dir]}"
OUTDIR="${2:-$(pwd)/chdman_build}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

MAME_SRC="$(realpath "$MAME_SRC")"
OUTDIR="$(realpath -m "$OUTDIR")"

# ---------------------------------------------------------------------------
# Validate MAME source tree
# ---------------------------------------------------------------------------
echo "==> Validating MAME source tree: $MAME_SRC"

for f in src/tools/chdman.cpp src/lib/util/hashing.cpp \
          src/osd/modules/file/winfile.cpp; do
    if [ ! -f "$MAME_SRC/$f" ]; then
        echo "ERROR: $MAME_SRC/$f not found."
        echo "       Make sure <mame-source-dir> points to a MAME source tree (0.286+)."
        exit 1
    fi
done

for d in 3rdparty/lzma 3rdparty/expat 3rdparty/flac 3rdparty/zstd 3rdparty/utf8proc; do
    if [ ! -d "$MAME_SRC/$d" ]; then
        echo "ERROR: $MAME_SRC/$d not found."
        exit 1
    fi
done

# ---------------------------------------------------------------------------
# Create output structure
# ---------------------------------------------------------------------------
echo "==> Creating output directory: $OUTDIR"
mkdir -p "$OUTDIR"

# ---------------------------------------------------------------------------
# Copy MAME source files
# ---------------------------------------------------------------------------
echo "==> Copying src/ ..."
cp -r "$MAME_SRC/src" "$OUTDIR/"

# version.cpp is generated by the MAME build system, not present in src/.
# Copy from build/generated/ if available, otherwise generate a minimal one.
if [ ! -f "$OUTDIR/src/version.cpp" ]; then
    if [ -f "$MAME_SRC/build/generated/version.cpp" ]; then
        cp "$MAME_SRC/build/generated/version.cpp" "$OUTDIR/src/version.cpp"
        echo "    version.cpp copied from build/generated/"
    else
        # Detect version from directory name (e.g. mame-mame0287 → 0.287)
        MAME_VER=$(basename "$MAME_SRC" | grep -oE '[1-9][0-9]{2,3}' | head -1)
        cat > "$OUTDIR/src/version.cpp" <<EOF
#define BARE_BUILD_VERSION "0.${MAME_VER}"
#define BARE_VCS_REVISION "unknown"
extern const char bare_build_version[];
extern const char bare_vcs_revision[];
extern const char build_version[];
const char bare_build_version[] = BARE_BUILD_VERSION;
const char bare_vcs_revision[]  = BARE_VCS_REVISION;
const char build_version[]      = BARE_BUILD_VERSION " (" BARE_VCS_REVISION ")";
EOF
        echo "    version.cpp generated (version 0.${MAME_VER})"
    fi
fi

echo "==> Copying 3rdparty/ ..."
mkdir -p "$OUTDIR/3rdparty"
for lib in lzma utf8proc expat zstd flac aes256cbc nanosvg; do
    if [ -d "$MAME_SRC/3rdparty/$lib" ]; then
        cp -r "$MAME_SRC/3rdparty/$lib" "$OUTDIR/3rdparty/"
    fi
done
# Note: zlib is intentionally excluded — replaced by zlib-ng

# ---------------------------------------------------------------------------
# Apply patches
# ---------------------------------------------------------------------------
echo "==> Applying patches ..."
cd "$OUTDIR"

for patch in \
    "$SCRIPT_DIR/patches/01_chdman_pipeline.patch" \
    "$SCRIPT_DIR/patches/02_winfile_sequential.patch" \
    "$SCRIPT_DIR/patches/03_hashing_simd.patch" \
    "$SCRIPT_DIR/patches/04_chdcodec_flac_lzma.patch" \
    "$SCRIPT_DIR/patches/05_chd_warning.patch"; do

    name="$(basename "$patch")"
    if patch -p1 --dry-run < "$patch" >/dev/null 2>&1; then
        patch -p1 < "$patch"
        echo "    [OK] $name"
    else
        echo "    [WARN] $name failed dry-run — attempting with --fuzz=5"
        if patch -p1 --fuzz=5 < "$patch"; then
            echo "    [OK] $name (with fuzz)"
        else
            echo "    [FAIL] $name — manual merge required. See patches/APPLY_PATCHES.md"
            echo "WARNING: patch $name was NOT applied. Binary will be incomplete." >&2
        fi
    fi
done

# ---------------------------------------------------------------------------
# Copy build files
# ---------------------------------------------------------------------------
echo "==> Copying Makefile and setup script ..."
cp "$SCRIPT_DIR/Makefile.standalone" "$OUTDIR/Makefile"
cp "$SCRIPT_DIR/setup_zlibng.sh"     "$OUTDIR/"
cp "$SCRIPT_DIR/README.md"           "$OUTDIR/"
cp "$SCRIPT_DIR/DELTA_OPTIMISATIONS.md" "$OUTDIR/"

# ---------------------------------------------------------------------------
# Build zlib-ng
# ---------------------------------------------------------------------------
echo "==> Building zlib-ng ..."
bash "$OUTDIR/setup_zlibng.sh"

# ---------------------------------------------------------------------------
# Build chdman
# ---------------------------------------------------------------------------
echo "==> Building chdman ..."
cd "$OUTDIR"
JOBS=$(nproc 2>/dev/null || echo 4)
# Prefer MSYS2 toolchain to avoid WinLibs/WinGet GCC in PATH
[ -d /c/msys64/mingw64/bin ] && export PATH=/c/msys64/mingw64/bin:$PATH
MAKE_BIN=$(which /c/msys64/mingw64/bin/mingw32-make 2>/dev/null \
        || which mingw32-make 2>/dev/null \
        || echo mingw32-make)
# Detect uasm here in bash (reliable PATH) and forward to make explicitly
if which uasm >/dev/null 2>&1 || which uasm.exe >/dev/null 2>&1; then
    echo "    uasm found — LZMA ASM decoder + LzFindOpt ASM enabled"
    MAKE_ASM_FLAG="HAVE_LZMA_ASM=1"
else
    echo "    uasm not found — C fallback"
    MAKE_ASM_FLAG=""
fi
"$MAKE_BIN" -j"$JOBS" $MAKE_ASM_FLAG

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "============================================================"
echo " Build complete!"
echo " Binary : $OUTDIR/chdman.exe"
echo " Test   : cd \"$OUTDIR\" && ./chdman.exe verify -i your.chd"
echo "============================================================"
